on:
  - push
  - pull_request
name: CI
jobs:
  spectralChecks:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test this action against an incorrect file.
        id: expect-failure
        uses: ./
        with:
          file_glob: ./fixtures/*.yml
          spectral_ruleset: .spectral.json
        continue-on-error: true

      - if: steps.expect-failure.output.status == 'failure'
        run: exit 0
